development:
  adapter: postgresql
  ncoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  username: pguser
  password: 27041984
  database: test
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: pguser
  password: 27041984
  database: test