development:
  adapter: postgresql
  ncoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: pguser
  password: 27041984
  database: test
production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 10
  port: 5432
  username: pguser
  timeout: 30000
  password: 27041984
  database: test
test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 10
  host: localhost
  port: 5432
  username: pguser
  password: 27041984
  database: test_test
